#!/bin/bash

set -eo pipefail

goveralls_path="${GOPATH}/bin/goveralls"

if [[ ! -x "${goveralls_path}" ]]; then
    go get -u github.com/mattn/goveralls
fi

SOURCE_DIRECTORY=$(dirname "${BASH_SOURCE[0]}")
cd "${SOURCE_DIRECTORY}/.."


do_analyze() {

    go test -covermode=count -coverprofile=coverage.out .

}

do_publish() {

    goveralls -coverprofile=coverage.out -service=travis-ci

}


case "$1" in
    --publish)
        do_publish
    ;;
    --analyze | *)
        do_analyze
    ;;
esac
exit 0
